<?php

declare(strict_types=1);

return [
    [
        'nombre' => 'Trabajador',
        'descripcion' => 'Personal de limpieza en terreno',
        'es_sistema' => 1,
        'permisos' => [
            'habitaciones.ver_asignadas_propias',
            'habitaciones.marcar_completada',
            'tickets.crear',
            'tickets.ver_propios',
            'copilot.usar_nivel_1_consultas',
            'copilot.usar_nivel_2_acciones',
            'copilot.ver_historial_propio',
            'kpis.ver_propios',
            'usuarios.cambiar_propia_contrasena',
            'usuarios.exportar_datos_propios',
            'disponibilidad.notificar_supervisora',
            'notificaciones.ver',
        ],
    ],
    [
        'nombre' => 'Supervisora',
        'descripcion' => 'Monitorea equipo, asigna y audita',
        'es_sistema' => 1,
        'permisos' => [
            'habitaciones.ver_todas',
            'habitaciones.ver_historial',
            'asignaciones.asignar_manual',
            'asignaciones.auto_asignar',
            'asignaciones.reordenar_cola_trabajador',
            'auditoria.ver_bandeja',
            'auditoria.aprobar',
            'auditoria.aprobar_con_observacion',
            'auditoria.rechazar',
            'auditoria.editar_checklist_durante_auditoria',
            'tickets.crear',
            'tickets.ver_todos',
            'turnos.ver',
            'copilot.usar_nivel_1_consultas',
            'copilot.usar_nivel_2_acciones',
            'copilot.ver_historial_propio',
            'kpis.ver_operativas',
            'alertas.recibir_predictivas',
            'usuarios.cambiar_propia_contrasena',
            'usuarios.exportar_datos_propios',
            'notificaciones.ver',
        ],
    ],
    [
        'nombre' => 'Recepción',
        'descripcion' => 'Audita habitaciones terminadas',
        'es_sistema' => 1,
        'permisos' => [
            'habitaciones.ver_todas',
            'auditoria.ver_bandeja',
            'auditoria.aprobar',
            'auditoria.aprobar_con_observacion',
            'auditoria.rechazar',
            'auditoria.editar_checklist_durante_auditoria',
            'copilot.usar_nivel_1_consultas',
            'copilot.usar_nivel_2_acciones',
            'copilot.ver_historial_propio',
            'usuarios.cambiar_propia_contrasena',
            'usuarios.exportar_datos_propios',
            'notificaciones.ver',
        ],
    ],
    [
        'nombre' => 'Admin',
        'descripcion' => 'Control total del sistema',
        'es_sistema' => 1,
        'permisos' => '__ALL__',
    ],
];
