<?php

declare(strict_types=1);

return [
    [
        'nombre' => 'Trabajador',
        'descripcion' => 'Personal de limpieza en terreno',
        'es_sistema' => 1,
        'permisos' => [
            'habitaciones.ver_asignadas_propias',
            'habitaciones.marcar_completada',
            'habitaciones.saltar',
            'cloudbeds.forzar_sincronizacion',
            'tickets.crear',
            'tickets.ver_propios',
            'copilot.usar_nivel_1_consultas',
            'copilot.usar_nivel_2_acciones',
            'copilot.ver_historial_propio',
            'kpis.ver_propios',
            'usuarios.cambiar_propia_contrasena',
            'usuarios.exportar_datos_propios',
            'disponibilidad.notificar_supervisora',
            'notificaciones.ver',
        ],
    ],
    [
        'nombre' => 'Supervisora',
        'descripcion' => 'Monitorea equipo, asigna y audita',
        'es_sistema' => 1,
        'permisos' => [
            'habitaciones.ver_todas',
            'habitaciones.ver_historial',
            'habitaciones.marcar_limpia_manual',
            'habitaciones.marcar_nochero',
            'habitaciones.agregar_nota',
            'habitaciones.gestionar_edificios',
            'asignaciones.asignar_manual',
            'asignaciones.auto_asignar',
            'asignaciones.reordenar_cola_trabajador',
            'espacios.ver',
            'espacios.crear_editar',
            'espacios.pedir_limpieza',
            'habitaciones.importar_inventario',
            'auditoria.ver_bandeja',
            'auditoria.aprobar',
            'auditoria.aprobar_con_observacion',
            'auditoria.rechazar',
            'auditoria.editar_checklist_durante_auditoria',
            'auditoria.reordenar_bandeja',
            'tickets.crear',
            'tickets.ver_todos',
            'turnos.ver',
            'turnos.crear_editar',
            'turnos.asignar_a_usuario',
            'copilot.usar_nivel_1_consultas',
            'copilot.usar_nivel_2_acciones',
            'copilot.ver_historial_propio',
            'kpis.ver_operativas',
            'alertas.recibir_predictivas',
            'apariencia.editar',
            // DEFAULT APLICADO (aprobado por el usuario, 04/10/2026): el catálogo de motivos y el
            // interruptor de la inspección pre-entrega los maneja supervisión, no Recepción (que cubre lo
            // imprevisto con «Otro» + observaciones). Se cambia desde Ajustes → Roles sin tocar código.
            'revision_entrega.configurar',
            'usuarios.cambiar_propia_contrasena',
            'usuarios.exportar_datos_propios',
            'notificaciones.ver',
            // Permisos de marca: no es personal de aseo (fuera de KPIs y del reparto automático, 04/10/2026).
            'kpis.excluido',
            'asignaciones.excluir_auto',
        ],
    ],
    [
        'nombre' => 'Recepción',
        'descripcion' => 'Audita habitaciones terminadas',
        'es_sistema' => 1,
        'permisos' => [
            'habitaciones.ver_todas',
            'habitaciones.marcar_nochero',
            'habitaciones.agregar_nota',
            'auditoria.ver_bandeja',
            'auditoria.aprobar',
            'auditoria.aprobar_con_observacion',
            'auditoria.rechazar',
            'auditoria.editar_checklist_durante_auditoria',
            'auditoria.reordenar_bandeja',
            // Inspección pre-entrega (04/10/2026): revisa la pieza antes de entregarla al huésped, desde
            // su tarjeta en Habitaciones. Sin habitaciones.gestionar_edificios (decisión de Nicolás, 05/10).
            'revision_entrega.registrar',
            'tickets.crear',
            'tickets.ver_todos',
            'copilot.usar_nivel_1_consultas',
            'copilot.usar_nivel_2_acciones',
            'copilot.ver_historial_propio',
            'usuarios.cambiar_propia_contrasena',
            'usuarios.exportar_datos_propios',
            'notificaciones.ver',
            // Permisos de marca: no es personal de aseo (fuera de KPIs y del reparto automático, 04/10/2026).
            'kpis.excluido',
            'asignaciones.excluir_auto',
        ],
    ],
    [
        'nombre' => 'Admin',
        'descripcion' => 'Control total del sistema',
        'es_sistema' => 1,
        'permisos' => '__ALL__',
    ],
    [
        // Personal de otras áreas que limpia de vez en cuando (01/10/2026): trabaja igual que un
        // Trabajador, pero no suma créditos, no entra en KPIs ni en el bono, y no recibe piezas del
        // reparto automático. No es de sistema: Admin puede editarlo o borrarlo desde Ajustes.
        'nombre' => 'Apoyo',
        'descripcion' => 'Personal de otras áreas que apoya en limpieza (sin créditos ni KPIs)',
        'es_sistema' => 0,
        'permisos' => [
            'habitaciones.ver_asignadas_propias',
            'habitaciones.marcar_completada',
            'habitaciones.saltar',
            'cloudbeds.forzar_sincronizacion',
            'tickets.crear',
            'tickets.ver_propios',
            'copilot.usar_nivel_1_consultas',
            'copilot.usar_nivel_2_acciones',
            'copilot.ver_historial_propio',
            'usuarios.cambiar_propia_contrasena',
            'usuarios.exportar_datos_propios',
            'disponibilidad.notificar_supervisora',
            'notificaciones.ver',
            'kpis.excluido',
            'asignaciones.excluir_auto',
        ],
    ],
];
